apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxcm
  name: nginxcm
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    volumeMounts:
    - name: cm
      mountPath: /etc/cm
  volumes:
  - name: cm
    configMap:
      name: prometheuscm
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
