apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cat.newname" . -}}-dpl
  labels:
    {{- include "cat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cat.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cat.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
