apiVersion: v1
kind: Service
metadata:
  name: {{ include "cat.newname" . -}}-svc
  labels:
    {{- include "cat.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.nodePort }}
  selector:
    {{- include "cat.labels" . | nindent 4 }}
