# Default values for cat.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

envLabel: dev

service:
  type: ClusterIP
  nodePort: ""
