apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-empty
  name: nginx-empty
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        port: 80
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/cache"
      name: pv-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: pv-storage
    emptyDir: {}
status: {}
