# apiVersion: v1
# kind: Pod
# metadata:
#   creationTimestamp: null
#   labels:
#     run: nginx
#   name: nginx
# spec:
#   containers:
#   - image: nginx
#     name: nginx
#     resources: {}
#     envFrom:
#       - secretRef:
#           name: my-secret
#   dnsPolicy: ClusterFirst
#   restartPolicy: Always
# status: {}
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxwithenv
  name: nginxwithenv
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
    env:
    - name: "USERNAME"
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: "PASSWORD"
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
