apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginxcorrectliveness
spec:
  containers:
  - image: nginx
    name: nginx
    livenessProbe:
      httpGet:
        port: 80
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
